name: flutter_sample_networking
description: Sample Flutter app for networking comparison (Compose Multiplatform vs Flutter) with Dio, timing, retry, and error mapping.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
